@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2YTUwOWFhZWE3ZTM0ZjE4MjljMTRkZWEiLCJuYW1lIjoiQ3Jpc3RpYW4gVG9uZSIsImVtYWlsIjoibmVsdWNyaXN0aWFuMjAwNUBnbWFpbC5jb20iLCJwcm9maWxlUGljIjoicHJvZmlsZVBpYy0xNzgzNjY3Mzc0OTI0LmpwZWciLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzgzOTQ4NTE5LCJleHAiOjE3ODM5NTIxMTl9.k-M0G-MWOEV3iJxmBcUig3ZKvRHbXUxeY9ZyuEfauDk

GET http://localhost:5000/api/order    
Content-Type: application/json
x-auth-token: {{token}}
